### ISSUE TITLE
ログイン周り作成

### ISSUE THREAD

**Issue by nebokecat** [mikik0/cat-quest#1]
- [x] devise導入
- [x] sign up周り
- [x] sign in周り

**Comment by riita10069** [comment]
I think that using devise(which is ruby gem) means implement email and password authentication.
OAuth and OpenIDConnect are also options, but these are not used in this app?
I'll leave the decision to the implementors.

**Comment by nebokecat** [comment]
設定変えれるから名前とpassの認証にする〜。OAuthとかはUserにそもそも大事な情報を持たせないようにしてるからそこまで認証をガチガチにする必要もないかなぁ〜って感じ。余裕があれば考えたいくらいかな現状

**Comment by riita10069** [comment]
え、おれなんで英語でかいたんだろうwww

**Comment by riita10069** [comment]
おっけ〜
Google認証するって言ってたような気がしたから、気になっただけ〜
