### ISSUE TITLE
画像のみをリンク化する

### ISSUE THREAD

**Issue by mikik0** [mikik0/cat-quest#21]
現在、横幅いっぱいにリンク化されているので困っている。
選択している右の黒い部分は謎にホバーがかかっていて、画像部分ではない！！
画像部分のみをリンク化して欲しい。

<img width="1680" alt="スクリーンショット 2021-08-19 18 44 46" src="https://user-images.githubusercontent.com/55236878/130082873-132decc2-886b-49a4-a416-e07ec81dea19.png">

**Comment by mona-apk** [comment]
このタスク見てみます

**Comment by mikik0** [comment]
#31 でやりました！
